import { Product } from "./types";

export const products : Product[] = [
    {
        id: 1,
        title : "Gray Hoodie",
        slug  :  "gray-hoodie",
        image : "/assets/p1.jpg",
        // slug: "black-jeans",
        price: 120,
        // discount: 0,
        category: "hoodie",
        size: ["XS","S","M","L","XL"],
        // color: ["#ffffff","#000000","#e60000"],
        qty:1,
    },
    {
        id: 2,
        title : "Cyan T-Shirt",
        slug  :  "cyan-t-shirt",
        image : "/assets/p7.jpeg",
        // slug: "black-jeans",
        price: 100,
        // discount: 0,
        category: "shirts",
        size: ["XS","S","M","L","XL"],
        // color: ["#ffffff","#000000","#e60000"],
        qty:1,
    },
    {
        id: 3,
        title : "Gray T-Shirt",
        slug  :  "gray-t-shirt",
        image : "/assets/p2.jpg",
        // slug: "black-jeans",
        price: 105,
        // discount: 0,
        category: "shirts",
        size: ["XS","S","M","L","XL"],
        // color: ["#ffffff","#000000","#e60000"],
        qty:1,
    },
    {
        id: 4,
        title : "Men Sweat Shirt",
        slug  :  "Men-Sweat-Shirt",
        image : "/assets/p4.jpg",
        // slug: "black-jeans",
        price: 100,
        // discount: 0,
        category: "shirts",
        size: ["XS","S","M","L","XL"],
        // color: ["#ffffff","#000000","#e60000"],
        qty:1,
    },
    {
        id: 5,
        title : "Green Dress Shirt",
        slug  :  "green-dress-shirt",
        image : "/assets/p5.jpg",
        // slug: "black-jeans",
        price: 80,
        // discount: 0,
        category: "shirts",
        size: ["XS","S","M","L","XL"],
        // color: ["#ffffff","#000000","#e60000"],
        qty:1,
    },
    {
        id: 6,
        title : "Men Blue Jeans",
        slug  :  "men-blue-jeans",
        image : "/assets/p3.jpg",
        // slug: "black-jeans",
        price: 70,
        // discount: 0,
        category: "pants",
        size: ["XS","S","M","L","XL"],
        // color: ["#ffffff","#000000","#e60000"],
        qty:1,
    },
    {
        id: 7,
        title : "Men Light Blue Jeans",
        slug  :  "men-light-blue-jeans",
        image : "/assets/p6.jpg",
        // slug: "black-jeans",
        price: 90,
        // discount: 0,
        category: "pants",
        size: ["XS","S","M","L","XL"],
        // color: ["#ffffff","#000000","#e60000"],
        qty:1,
    },
    {
        id: 8,
        title : "Men Black Jeans",
        slug  :  "men-black-jeans",
        image : "/assets/p8.jpg",
        // slug: "black-jeans",
        price: 100,
        // discount: 0,
        category: "pants",
        size: ["XS","S","M","L","XL"],
        // color: ["#ffffff","#000000","#e60000"],
        qty:1,
    },
    {
        id: 9,
        title : "Black Sneakers",
        slug  :  "black-sneakers",
        image : "/assets/p9.jpg",
        // slug: "black-jeans",
        price: 150,
        // discount: 0,
        category: "shoes",
        size: ["XS","S","M","L","XL"],
        // color: ["#ffffff","#000000","#e60000"],
        qty:1,
    },
    {
        id: 10,
        title : "Special Sneakers",
        slug  :  "special-sneakers",
        image : "/assets/p10.jpg",
        // slug: "black-jeans",
        price: 140,
        // discount: 0,
        category: "shoes",
        size: ["XS","S","M","L","XL"],
        // color: ["#ffffff","#000000","#e60000"],
        qty:1,
    },
  
]